version: '3.8'

services:
  frontend:
    build: ./facturaview
    ports:
      - "5173:5173"
    volumes:
      - ./facturaview:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build: ./facturaapi
    ports:
      - "8000:8000"
    volumes:
      - ./facturaapi:/app
    working_dir: /app
